# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=120),
        ),
    ]
