# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0002_auto_20180129_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
