# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0003_item_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item_name',
            new_name='item_name',
        ),
    ]
