# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0004_auto_20180129_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_boy_name', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('pick_up_time', models.TimeField()),
                ('delivery_time', models.TimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citimeal.Order')),
            ],
        ),
    ]
