# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0005_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
