# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0006_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
