# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0007_auto_20180130_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered')], default='shipped', max_length=120),
        ),
    ]
