# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0008_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Total', models.IntegerField()),
                ('order', models.ManyToManyField(to='citimeal.Order')),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citimeal.Order'),
        ),
    ]
