# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0010_auto_20180130_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desciption',
            new_name='description',
        ),
    ]
