# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citimeal', '0011_auto_20180204_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='citimeal.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citimeal.User')),
            ],
        ),
    ]
