# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile_no',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=120),
        ),
    ]
