# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cart_products'),
        ('items', '0002_auto_20171218_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='items.Item'),
        ),
    ]
