# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='subtotal',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
