# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20171218_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
    ]
