# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20171220_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
