# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20171220_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
    ]
