# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20171220_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='featured',
        ),
    ]
