# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
